//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

public partial class Default {
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;
    protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
    protected global::System.Web.UI.WebControls.Button LoginButton;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl ErrorWrapper;
    protected global::System.Web.UI.WebControls.Literal ErrorMessageText;
}
